### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by sneakywombat** [google/capirca#100]
We've been on version 1.109 for a very long time.  Can we discuss options to increment this on a regular basis?  I don't really care how, just as long as it changes :)

@ankenyr thoughts?

**Comment by ankenyr** [comment]
Sure, do you care how frequently it changes? Should it be done on every commit or some other pattern?

**Comment by morrowc** [comment]
At Fri, 14 Oct 2016 10:27:13 -0700,
Rob <notifications@github.com> wrote:
> 
> Sure, do you care how frequently it
> changes? Should it be done on every commit or some other pattern?
> 

why not something sane like monthly releases if there are changes committed?
(surely there's automated testing and such that could kick out a new release)

**Comment by sneakywombat** [comment]
Either sound fine, or even a monthly to keep the volume low, assuming there
are changes.

**Comment by ankenyr** [comment]
I will need to see if anyone else has anything to easily automate this. Currently I use [MOE](https://github.com/google/moe) to push things out and it is a manual process. For the time being I can easily increment it every month manually. Will do the first one once I complete migrating #96 into our internal repo.

**Comment by finfinack** [comment]
I would have probably increased with each change that changes behavior or
for simplicity with every patch. That should make tracking issues down more
easy as well. If there are automated releases with tarballs and all at some
point that makes sense but until then I'd propose to increase minor
versions with each patch.

Also see: https://en.m.wikipedia.org/wiki/Software_versioning

**Comment by ankenyr** [comment]
MOE allows you to add some shell scripts that get run. I need to make one that more properly sorts the imports. Mock internal needs to come at the end of the capirca lib imports but external it needs to come before. I think I could make a script that could increment the version numbers with [bumpversion](https://pypi.python.org/pypi/bumpversion).
Patches increment the patch version, new files increment minor version. Major version not sure when I would want to increment that.

**Comment by finfinack** [comment]
That sounds good to me to start with. I'm not a big fan of "new file ==
minor version increase" personally as imo minor version increase should
happen as well when an existing generator is rewritten for example but it's
probably a good enough approximation to begin with.

I'd say major version is increased manually and happens rarely e.g. when
there's bigger rewrites or so.

**Comment by sneakywombat** [comment]
ping. 👍

**Comment by ankenyr** [comment]
Pong!
Just incremented it now. Sorry about that. Will try to do this more frequently. Thanks for the reminder @sneakywombat

**Comment by sneakywombat** [comment]
Thanks!
