### ISSUE TITLE
Capirca exists silently if policy file has no target line

### ISSUE THREAD

**Issue by dylaan** [google/capirca#101]
Title says it all. Feel free to close if pedantic, but we're experimenting with automatic creation of policy files, and some hair was pulled trying to identify the mistake.

**Comment by ankenyr** [comment]
Sorry that you had some problems. Was there a specific thing you were trying to accomplish by not adding a target line or were you confused about how things work?

**Comment by dylaan** [comment]
@ankenyr I have some code which automatically generates policy files used by capirca. I didn't realise a change in my code was causing the target lines to be omitted completely. Is there any reasonable case where no target lines would be desirable? If not, should an error be thrown?

**Comment by ankenyr** [comment]
I don't see any reason why you would want that. Should be a simple fix, do you wish to make a PR?

**Comment by ankenyr** [comment]
Going to close this. Please send a PR if you wish to fix this.
