### ISSUE TITLE
ASA and IOS use same policy copy

### ISSUE THREAD

**Issue by sjtarik** [google/capirca#106]
Both Cisco and Cisco ASA use the same copy of policy object. Will this create an issue for single worker case for multiple targets (Cisco and ASA)?

    if acl:
      acl_obj = cisco.Cisco(acl, exp_info)
      RenderACL(str(acl_obj), acl_obj.SUFFIX, output_directory,
                input_file, write_files)
    if asacl:
      acl_obj = ciscoasa.CiscoASA(acl, exp_info)
      RenderACL(str(acl_obj), acl_obj.SUFFIX, output_directory,
                input_file, write_files)

**Comment by MixMuffins** [comment]
Acknowledged. I'll look into this tomorrow.

**Comment by ankenyr** [comment]
I fixed this in ec6916f3ecc46f27a991bd877c8e3f0b8aac5343
