### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by sneakywombat** [google/capirca#110]
@ankenyr, I'd like to open up a discussion about python3 support.  As the [countdown clock](https://pythonclock.org/) points out, this is a decision we'll need to confront at some point.  In an effort to get this dialog started, I submitted a [PR](https://github.com/google/capirca/pull/109) to add future imports to all of the python files we have.  I'll be following the recommendations [here](http://python-future.org/quickstart.html) and [here](https://docs.python.org/3/howto/pyporting.html).  One item of note that the [PR](https://github.com/google/capirca/pull/109) brings up is this:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
```

This is the big key to writing python2.7/3 compatible code.  It isn't the whole story, but it's the first part of it.  The big question I have is how long should we support python2.7?  Supporting only 3.5 and up will let us do some things that would give us some perf gains.  Supporting both might slow things down a little.  So supporting both isn't without a cost.  Thoughts?

**Comment by sneakywombat** [comment]
@ankenyr any thoughts on this one?

**Comment by ankenyr** [comment]
Currently there are things preventing adoption of Python 3 for Capirca internal to Google. Unfortunately these things are outside of my control but they are being worked on. I agree supporting two versions is not optimal and will make things a bit slow.  Until we can move ourselves internal to 3 we will need to support 2.7. At the very latest I expect it to be resolved by the end of 2017 though I hope it will be done a lot sooner than that.

I am going to add this to our roadmap in the wiki. I will leave this issue open for a little while for others to chime in if they want.

**Comment by sneakywombat** [comment]
Totally understand.  So as long as we maintain dual version support, it's cool?

**Comment by ankenyr** [comment]
Yup, once we can move internally over to python 3 I expect we will drop 2.7. Does that sound fine to you and anyone else? Would it be preferred if I give some head notice before a change to pure python 3?

**Comment by sneakywombat** [comment]
sounds good to me.
