### ISSUE TITLE
Add doc for the SRXlo target

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#112]
Tried to look at the SRXlo target but can't find the differences with the "standard" SRX?
Would it be possible to add some docs about it to the wiki?

**Comment by vklimovs** [comment]
SRXlo target is interesting. SRX loopback policies, which this targer is for, are actually normal Juniper stateless ACLs. Except there are small differences, and that's why generator inherits from Juniper one and changes couple of things. But yeah, documentation would be good.

**Comment by XioNoX** [comment]
Yeah, it's those small differences that I'm interested about. I currently use a "standard" Juniper stateless firewall filters for my loopbacks.

**Comment by ankenyr** [comment]
Added something small to the documentation about the srxlo.py generator. The only real difference looks to be changes to ICMP normalization
