### ISSUE TITLE
aclgen.py "gflags.FlagsError: Flag name must be a string"

### ISSUE THREAD

**Issue by zombah** [google/capirca#114]
Hello,
I just pulled latest master and encountered this error:
`
./aclgen.py                                                                                                                                                                  
Traceback (most recent call last):  
  File "aclgen.py", line 67, in <module>  
    'The base directory to look for acls; '  
  File "/usr/lib/python2.7/dist-packages/gflags.py", line 2155, in DEFINE_string  
    DEFINE(parser, name, default, help, flag_values, serializer, **args)  
  File "/usr/lib/python2.7/dist-packages/gflags.py", line 2019, in DEFINE  
    flag_values)  
  File "/usr/lib/python2.7/dist-packages/gflags.py", line 2034, in DEFINE_flag  
    fv[flag.name] = flag  
  File "/usr/lib/python2.7/dist-packages/gflags.py", line 898, in __setitem__  
    raise FlagsError("Flag name must be a string")  
gflags.FlagsError: Flag name must be a string  
`

last working commit was e2eece0dac798fe08cf107bf37661b3322757b25

Bisecting points to this commit:
`
Bisecting: 0 revisions left to test after this (roughly 1 step)
[0ae35f5965b5862912c91431dbd668b5de374b4b] add __futures__ to all python files to support python2.7/3 code
`
Maybe i need to update something from requirements list to fix this?

**Comment by ankenyr** [comment]
How did you go about installing the package? pip? setup.py? What platform are you on? What version of the required libraries are you on?

**Comment by zombah** [comment]
openSUSE Leap 42.2 on x86_64. Capirca only cloned with git clone and dependencies installed from openSUSE repo their versions below:
i | python-PyYAML                       | package    | 3.11-6.3                           | x86_64 | openSUSE-Leap-42.2-Oss
i | python-ipaddr                       | package    | 2.1.10-17.1                        | noarch | openSUSE-Leap-42.2-Oss
i | python-mock                         | package    | 2.0.0-2.1                          | noarch | openSUSE-Leap-42.2-Oss
i | python-python-gflags                | package    | 2.0-8.3                            | noarch | openSUSE-Leap-42.2-Oss
i | python-six                          | package    | 1.9.0-6.2                          | noarch | openSUSE-Leap-42.2-Oss
i | python-ply                          | package    | 3.9-1.1                            | noarch | openSUSE-Leap-42.2-Oss 

If i revert back to e2eece0dac798fe08cf107bf37661b3322757b25 everything working again without such errors.

**Comment by ankenyr** [comment]
I was able to reproduce this. You need to upgrade your gflags library to 3.0 or greater. I will leave this open and make sure to note that as a requirement in the files or you can submit a PR.

**Comment by zombah** [comment]
Confirmed. Updating python-gflags to version 3.1.1 fixes this error. 
Thank you.

**Comment by zombah** [comment]
Submitted PR #117
