### ISSUE TITLE
Upload Capirca to PyPI

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#116]
It would be very convenient to be able to install Capirca with "pip install capirca"

For that the package maintainer needs to follow this documentation:
https://packaging.python.org/distributing/#uploading-your-project-to-pypi

**Comment by mirceaulinic** [comment]
+1

**Comment by jschlyter** [comment]
+1

**Comment by bewing** [comment]
+1

**Comment by ankenyr** [comment]
https://pypi.python.org/pypi/capirca

Going to add more to it and work on signing the code but it looks like it is working.

**Comment by XioNoX** [comment]
I'm getting the following issue when running
> pip install capirca

```
    running install_data
    warning: install_data: setup script did not provide a directory for 'aclcheck_cmdline.py' -- installing right in '/[...]/net-conf-gen/env'    
    error: can't copy 'aclcheck_cmdline.py': doesn't exist or not a regular file
```

**Comment by ankenyr** [comment]
Should be good now, tested this in a virtual environment. Had some problems with the upload and it seems you cannot delete and reupload. I will include documentation internally for us for testing the release before we proceed for future releases. If someone on here can confirm just to make sure I am not crazy.

**Comment by XioNoX** [comment]
So I don't know anything about pypi and packaging. Looking at other libraries (like napalm_junos, ipaddr) I think:
 - test/sample data should be removed, to make the package lighter and only contain the librarry and executable files
 - aclgen.py/aclcheck_cmdline.py/definate.py should be moved to the bin/ directory, and have their .py extension removed, so they can be called with "aclgen/aclcheck_cmdline/definate" anywhere as long as the virtualenv has been activated, regardless of the name of the venv.
 - It's still not possible to do "import capirca" in a python shell after initializing the venv. I think it's because the library needs to end up in lib/python2.7/site-packages/ not sure about the exact format

**Comment by ankenyr** [comment]
I believe this is in a good state now. Going to mark this as closed.
