### ISSUE TITLE
Any good way to build the policy object and send it to the aclgenerator?

### ISSUE THREAD

**Issue by mirceaulinic** [google/capirca#122]
Hello,

I've been looking into this and I wasn't able to find any good way to send the `pol` object to the ACLGenerator.

My idea would be to jump over the file processing part and instantiate directly the rendering class.
If I am not able to express very well what I have in mind, please let's look at the following example:

```python
pol = {...}  # somehow it has all the necessary bits
j = aclgen.juniper.Juniper(pol, 0)
```

Without reading a file from the disk etc.
Is there any good way to do this?

Thanks,
Mircea

**Comment by ankenyr** [comment]
Not currently. The creation of the policy object calls AddFilter which in turn calls Translate policy which will error out because no terms are present. You could comment that out and possibly be able to create a blank policy object. What are you trying to do that requires a blank object?

**Comment by mirceaulinic** [comment]
Hi @ankenyr - thanks for your answer!

I'm not really interested into creating a blank object, but more rather to be able to generate a policy config given an object with entities of data.

I can hack something, but it's going to be pretty painful, for example:

```python
import aclgen

class Header:
    def __init__(self):
        self.platforms = ['juniper']

class Term(dict):
    def __init__(self):
        self.platform = 'juniper'
        self.platform_exclude = None

class Policy:
    def __init__(self):
        header = Header()
        term = Term()
        terms = [term]
        self.filters = [(header, terms)]

p = Policy()
aclgen.juniper.Juniper(p, 0)
```

The lines above would be just the initial steps... and this will fail at some point.

What I'd be interested is the following: keep the policy config info in a certain object and use it later to generate the config, e.g.:

```python
class MyPolicy:
    def __init__(self):
        self.protocol = 'tcp'
        self.destination_address: '1.2.3.4'
```
etc.

Is this anything better? Please let me know if this isn't clear enough what I'd like to achieve.

Thanks,
Mircea

**Comment by ankenyr** [comment]
Hey Mircea,
We don't have anything built to help with this besides policy.py and policy_simple.py. You should be able to inherit from those and overwrite the things you want.
Going to close this topic but feel free to reopen if you have further questions.

**Comment by mirceaulinic** [comment]
Hi @ankenyr,

Thank you for clarifying this.
Would you mind expanding on this a little bit more?
I think I have an idea, but you are much more comfortable with the library than I do.
Let's say you define a tiny policy with one single parameter, e.g. `destination-address` - how would you create such an object.
And I promise this would be my very last question & if there's an easier way than the dirty hack I have presented above, I will come back with something that the community will definitely like :)

Thanks,
Mircea

**Comment by ankenyr** [comment]
No worries,
So if I understand what you want you want to make a policy object that is statically set to certain things. Such as platform being Juniper or adding a term into it right?


```

from lib import juniper
from lib import naming
from lib import policy


class MyPolicy(policy.Policy):

  def __init__(self):
    self.filters = []
    self.filename = ''


class MyTerm(policy.Term):

  def __init__(self):
    self.name = None
    self.action = []
    self.address = []
    self.address_exclude = []
    self.comment = []
    self.counter = None
    self.expiration = None
    self.destination_address = []
    self.destination_address_exclude = []
    self.destination_port = []
    self.destination_prefix = []
    self.forwarding_class = []
    self.forwarding_class_except = []
    self.logging = []
    self.log_name = None
    self.loss_priority = None
    self.option = []
    self.owner = None
    self.policer = None
    self.port = []
    self.precedence = []
    self.principals = []
    self.protocol = []
    self.protocol_except = []
    self.qos = None
    self.pan_application = []
    self.routing_instance = None
    self.source_address = []
    self.source_address_exclude = []
    self.source_port = []
    self.source_prefix = []
    self.verbatim = []
    # juniper specific.
    self.packet_length = None
    self.fragment_offset = None
    self.hop_limit = None
    self.icmp_type = []
    self.ether_type = []
    self.traffic_class_count = None
    self.traffic_type = []
    self.translated = False
    self.dscp_set = None
    self.dscp_match = []
    self.dscp_except = []
    self.next_ip = None
    self.flexible_match_range = []
    self.source_prefix_except = []
    self.destination_prefix_except = []
    # srx specific
    self.vpn = None
    # gce specific
    self.source_tag = []
    self.destination_tag = []
    # iptables specific
    self.source_interface = None
    self.destination_interface = None
    self.platform = []
    self.platform_exclude = []
    self.timeout = None
    self.flattened = False
    self.flattened_addr = None
    self.flattened_saddr = None
    self.flattened_daddr = None
    # include all other pieces but exclude the AddObject at the end


definitions = naming.Naming('def')
foo = MyPolicy()
header = policy.Header()
tar = policy.Target(['juniper','foo'])
header.AddObject(tar)


bar = MyTerm()
bar.name = 'test-term'
bar.destination_address = definitions.GetNet('RFC1918')
bar.action = ['accept']

foo.filters = [(header,[bar])]

jcl = juniper.Juniper(foo, 2)
print(jcl)

```

This would output

```
firewall {
    family inet {
        replace:
        /*
        ** $Id:$
        ** $Date:$
        ** $Revision:$
        **
        */
        filter foo {
            interface-specific;
            term test-term {
                from {
                    destination-address {
                        /* non-public */
                        10.0.0.0/8;
                        /* non-public */
                        172.16.0.0/12;
                        /* non-public */
                        192.168.0.0/16;
                    }
                }
                then accept;
            }
        }
    }
}
```

Let me know if this helps you.

**Comment by mirceaulinic** [comment]
Yes, I had something similar in mind too.
Thank you very much for expanding on this together and detailed explanation @ankenyr!

Cheers,
Mircea
