### ISSUE TITLE
nsxv mixed mode rendering incorrectly 

### ISSUE THREAD

**Issue by xmin0s** [google/capirca#129]
For the nsxv lib when using mixed mode (vs inet/inet6) it will incorrectly exit rendering when there isn't a source or destination specified. 

Line 225 breaks this for source-address:
https://github.com/google/capirca/blob/master/lib/nsxv.py#L225

Line 245 breaks this for destination-address:
https://github.com/google/capirca/blob/master/lib/nsxv.py#L245

Simply commenting out the return '' statement on both will fix mixed mode rendering. It's worth while to mention this would only be hit when there isn't a source specified (e.g. any is the desired config) or a destination isn't specified. Both conditions will cause rendering to cease and you'll end up with basically just what the header renders and 
    <section> </section>. 

A fairly easy fix. I'd submit a diff but I currently don't have access from my @fb account.

**Comment by SecurityForDotes** [comment]
I'll take a look at this and report back.

**Comment by SecurityForDotes** [comment]
This was resolved.

Thanks!
