### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by kenfire** [google/capirca#130]
Hello,
I am trying to install capirca but I am having issues. I tried to see the wiki but it might be outdated.
If someone could add examples in the README it would be nice.

Thank you.

**Comment by ankenyr** [comment]
Hi, is there an error you are getting? How are you trying to install it and
what commands are you running?

**Comment by ankenyr** [comment]
Hi @kenfire now that I am back at my desk (you caught me at my afternoon run) it looks like I may be seeing what you are seeing. Is it either cgrep or a maximum recursion reached error? cgrep should be fixed, the maximum recursion error we are looking at now but this looks to be something wrong with a package we require and not ours.

**Comment by kenfire** [comment]
@ankenyr Thank you taking time to answer.

I switched to my home PC and actually this did fine:
`sudo pip install -r requirements.txt`
`sudo python setup.py install`

(Debian Jessie: did not work; Kali rolling: works)

Otherwise, from what I remember, yes it was an error involving cgrep.

**Comment by ankenyr** [comment]
Yea try pulling in the latest and the cgrep error should be fine. That being said Travis is currently failing from a previous commit cc9192ac83b873156d5c06644e61857b4c614b61. @SecurityForDotes is working on fixing it now. If you get a recursive error let me know, it looks to be an issue with the mock library requirement with setup.py but I have not had a chance to replicate it.

**Comment by kenfire** [comment]
Pulled and the error vanished :)
Now I am having errors when doing
`sudo python aclgen.py`

```
WARNING:root:WARNING: Term accept-traceroute in policy LOOPBACK is expired and will not be rendered.
WARNING:root:WARNING: Term accept-traceroute in policy LOOPBACK is expired and will not be rendered.
WARNING:root:WARNING: Term accept-traceroute in policy LOOPBACK is expired and will not be rendered.
WARNING:root:

error encountered in rendering process:
Error parsing policy file ./build/lib.linux-x86_64-2.7/tests/characterization_data/policies/pol/sample_multitarget.pol:
<class 'lib.policy.FileNotFoundError'>Unable to open policy file ./includes/untrusted-networks-blocking.inc


Traceback (most recent call last):
  File "aclgen.py", line 535, in <module>
    main(sys.argv)
  File "aclgen.py", line 520, in main
    result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
lib.nsxv.UnsupportedNsxvAccessListError: Access list type 1009 not supported by nsxv (good types: [u'inet', u'inet6', u'mixed'])
```

Should I create another issue ? (Don't know if related)
@ankenyr Thank you again.

**Comment by ankenyr** [comment]
They are not related but I don't think another issue is needed. the nsxv error was fixed by @SecurityForDotes recently I believe. The travis tests should be passing with his last commit.
Please pull down the latest and the run the following command
```
python aclgen.py --base_directory policies/
```

This should output the rendered files to where you ran this from. You can change the output directory with another flag.

I will leave this open, let me know if this does or does not work.

**Comment by kenfire** [comment]
Actually I found another problem when using this command:
`$ sudo ./aclgen.py --help`
```
Traceback (most recent call last):
  File "./aclgen.py", line 535, in <module>
    main(sys.argv)
  File "./aclgen.py", line 470, in main
    FLAGS(args)
  File "/usr/local/lib/python2.7/dist-packages/gflags/flagvalues.py", line 708, in __call__
    name, value, suggestions=suggestions)
gflags.exceptions.UnrecognizedFlagError: Unknown command line flag 'help'
```

But I found a fix :

<aclgen.py>
```
def main(args):
  try : FLAGS(args)
  except flags.FlagsError as e:
      print("%s\nUsage: %s ARGS\n%s" % (e, sys.argv[0], FLAGS))
      sys.exit(0)
```
Hope this will help.
PS: I might create a pull request.
