### ISSUE TITLE
NSXV generator inet_version mixed outputs invalid mix of IPv6 <-> IPv4 (when only thing on each side)

### ISSUE THREAD

**Issue by SecurityForDotes** [google/capirca#137]
The nsxv generator behaves incorrectly when inet_version mixed (in the header) is used and the source and dest have opposite inet_version for the terms.

Example:
if SourceAddress contains only IPv4 addresses
if DestinationAddress contains only IPv6 addresses

Then currently it outputs an ACL, when in fact it shouldn't because that's not a valid combination (same if source and dest are flipped.

I  think some valid combinations are (non exhaustive):
“any” to IPv6 
IPv6 to “any”
IPv6 to IPv6
IPv6+IPv4 to IPv6+IPv4
“any” to IPv4
IPv4 to “any”
IPv4 to IPv4
IPv4 to IPv4 +IPv6 (results in IPv6 being dropped from term and vice versa)
IPv6 to IPv6 +IPv4 (results in IPv4 being dropped from term and vice versa)

IE: it has to be balanced, and matched.

Given the following cases It looks like a number of them are obviously wrong:
mixed-to-v6
mixed-to-v4
mixed-to-mixed
v4-to-mixed
v4-to-v4
v4-to-v6
v6-to-v6

Mixed means the address object contains both IPv4 and IPv6 addresses. I believe the broken cases are:
mixed-to-v6
mixed-to-v4
mixed-to-mixed
v4-to-mixed
v4-to-v4
v4-to-v6

Might be fallout from: https://github.com/google/capirca/issues/129

**Comment by rarcotvmw** [comment]
I do see an issue with the mixed filter.
For mixed filter, the generator generates both IPV4 and IPV6 addresses for source and destination and there are no validations for some of the cases mentioned. Will work on the fix.

**Comment by ankenyr** [comment]
Can we resolve this now @SecurityForDotes ?

**Comment by SecurityForDotes** [comment]
Yup.
