### ISSUE TITLE
application term limit with icmpv6 types

### ISSUE THREAD

**Issue by sjtarik** [google/capirca#158]
Receiving following error message with icmpv6 term below. I think this is related to #30 , need to be addressed for icmpv6 types using application-sets similar to tcp/udp.

> bad_element: term, message: error: mgd: number of elements exceeds limit of 8\nerror: commit failed: (number of elements exceeds limit

```
term ALLOW-GOOD-ICMP-V6 {
  source-address:: ANY_IP
  protocol:: icmpv6
  icmp-type:: router-solicit router-advertisement neighbor-solicit neighbor-advertisement inverse-neighbor-discovery-solicitation inverse-neighbor-discovery-advertisement destination-unreachable packet-too-big time-exceeded parameter-problem echo-request echo-reply
  action:: accept
  logging:: true
}
```

**Comment by ankenyr** [comment]
Yea looks similar to that. Can you confirm if adding each of these to their own applications and putting them all into a set would work similar to how we do it for TCP? I don't have access to an SRX over this weekend and won't be able to check for a bit. Feel free to send out a CL to fix this if you can. I attached a pol file and the resulting srx file which includes your example plus one I made to compare it to how we handle tcp/udp applications.
[sample_srx.srx.txt](https://github.com/google/capirca/files/2298899/sample_srx.srx.txt)
[sample_srx.pol.txt](https://github.com/google/capirca/files/2298900/sample_srx.pol.txt)

**Comment by sjtarik** [comment]
Yeah, when divided up to multiple application-set's, it works on Junos. Sure, I can send out a CR in a few days.

**Comment by greenpau** [comment]
Stale issue.
