### ISSUE TITLE
Move capirca to use ipaddress instead of ipaddr

### ISSUE THREAD

**Issue by ankenyr** [google/capirca#159]
From https://github.com/google/ipaddr-py

> ipaddr.py is a library for working with IP addresses, both IPv4 and IPv6.
> 
> It has been superseded by ipaddress from the Python 3 standard library, and its
> Python 2 backport.

ipaddr is not compatible with Python3 and we would need to switch over to using ipaddress instead.

This is blocking #154

**Comment by ankenyr** [comment]
Ok update on the status. I got most tests passing but some small issues that are not covered by tests still crop up. Basically there are issues with using deepcopy with ipaddress. Got a bit more work to do on this.

**Comment by ankenyr** [comment]
Code is submitted internally, going to let it sit for a bit to make sure we don't have any problems. I will then push it out to public, ETA is end of next week.

**Comment by ankenyr** [comment]
We had a rollback which set this back a bit, will be pushing the change out mid next week at this point.

**Comment by ankenyr** [comment]
Seems there is a difference between the backport of ipaddress for python 2 and 3 compatibility and the ipaddress used in the python3 standard library which makes this a bit more complicated.

Specifically subnet membership is done in a way that makes us unable to use it given the current methods. I could easily just copy/paste the methods from the old version in and call it a day but that seems kinda crappy.

Started communications with one of the maintainers I know of the library to see if this would be accepted. If not we can add the required methods to nacaddr instead.

**Comment by nero85** [comment]
Closing issues migration to py3 has been completed.
