### ISSUE TITLE
Generate capirca policy file from access-list

### ISSUE THREAD

**Issue by nitinics** [google/capirca#182]
Any helper utils for converting existing ACLs to Capirca policy format? 

Ideally, from an access-list format, we could create a policy file matching network and service definitions. To make it simpler - let's say would only work if every definitions are strictly there.

**Comment by ankenyr** [comment]
Creating this would require creating a parser for the syntax of what ever platform we are talking about. Since creating a parser for each platform would be a very large task and the vendors do not wish to supply their parser it is infeasible to create this kind of tool.
