### ISSUE TITLE
aclgen command n

### ISSUE THREAD

**Issue by redNixon** [google/capirca#194]
The refactor that 6a555703d78bb824df3c6410888f12d2d7300ad8 implemented removed the entrypoint() function from aclgen.py in favor of calling main(argv) more directly.  This breaks the aclgen command that gets installed into the environment's path via the entrypoint.console_scripts section of setup.py.  Running aclgen on the command line via the scripts wrapper causes an exception to be thrown due to entry_point no longer existing
```
$ aclgen --help
Traceback (most recent call last):
  File "/virtual/environment /bin/aclgen", line 5, in <module>
    from capirca.aclgen import entry_point
ImportError: cannot import name 'entry_point'
```

The most obvious way of fixing the cli app by changing console_scripts to point to capirca.aclgen:main will not work since main takes a positional argument and console_scripts will not call the target with any args.  Reverting the removal of entry_point so that it is again wrapping main(argv) with entry_point() would not be a complete fix because of a few other exception producing lines in the main(argv) that were also introduced in this change but #193 looks to fixing some of these.

**Comment by ankenyr** [comment]
You are right it does seem to break things. Sadly while I was out for a while on paternity and a few commits slipped in by individuals who were unaware that they could break the open source version. My first goal right now is to get both code bases in sync again and then fix or revert the problematic changes.

**Comment by taliamax** [comment]
Should be fixed from https://github.com/google/capirca/commit/89a9c15153ab880833fe953a4ecd3455d2c07f84
