### ISSUE TITLE
Make the use of repository tags configurable/optional

### ISSUE THREAD

**Issue by fischa** [google/capirca#217]
After the discussion in Slack I'm proposing to make the use of the (only? with perforce/cvs useful) repository tags configurable via a parameter in the `target::` line of a policy.
I guess a similar approach as the `not-interface-specific` in juniper.py should do the trick. To not break backwards compatibility I would assume the current behavior as default and drop the repository tags only if the parameter is present. 

What do you think?

**Comment by fischa** [comment]
As discussed in Slack I'll prepare a PR but the CLA work got me delayed. Still waiting for being added to my employer's google group to meet the initial requirements.

**Comment by nero85** [comment]
Already fixed internally, closing issue.
