### ISSUE TITLE
Redeclaring PortMap object in lib/cisco.py

### ISSUE THREAD

**Issue by sjtarik** [google/capirca#218]
It seems like L290 and L451 has two definitions of the same object PortMap? Is one of them supposed to be indented within another object/class?

https://github.com/google/capirca/blob/198ade3cbaf1f6f4c3ea00e6c293ca950bd9fda0/capirca/lib/cisco.py#L290
https://github.com/google/capirca/blob/198ade3cbaf1f6f4c3ea00e6c293ca950bd9fda0/capirca/lib/cisco.py#L451

**Comment by rdsharma** [comment]
Thanks for the report! Should be fixed now.

**Comment by sjtarik** [comment]
Thank you. Can you tackle the other one about  Cisco ASA? You literally need to delete a fee spaces for it to work?

Tarik
