### ISSUE TITLE
Aclcheck.py thinks IP does not include TCP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/capirca#22]
```
What steps will reproduce the problem?
1. create term using "protocol:: ip:

term block-stuff {
  source-address:: MY_NETWORKS
  protocol:: ip
  logging:: true
  action:: deny
}

2.

Use ./aclcheck_cmdline.py to test the ACL with --proto ip. It works.
IP address 1.2.3.4 is in MY_NETWORKS.

./aclcheck_cmdline.py -p policies/toSERV03-WCM-IFZ.pol -s 1.2.3.4 -d 5.6.7.8 
--dport 80 --proto ip
  filter: toSERV03-WCM-IFZ
          term: block-stuff
                deny


3.

Use ./aclcheck_cmdline.py to test the ACL with --proto tcp. It *should* work 
just like the case above, since it is supposed to block all IP packets; but it 
does not. It rolls over the next term.

./aclcheck_cmdline.py -p policies/toSERV03-WCM-IFZ.pol -s 1.2.3.4 -d 5.6.7.8 
--dport 80 --proto tcp
  filter: toSERV03-WCM-IFZ
          term: default-deny
                deny


What version of the product are you using? On what operating system?

r145 with minor modifications on linux RHEL5.

Please provide any additional information below.


```

Original issue reported on code.google.com by `antonio....@gmail.com` on 23 Sep 2011 at 10:34

**Comment by ankenyr** [comment]
I am going to mark this as closed. 
From our wiki
> protocol:: the network protocols this term will match, such as tcp, udp, icmp, or a numeric value.
You can find a list of all protos here https://github.com/google/capirca/blob/master/lib/aclgenerator.py#L73

I don't believe this syntax is valid and what may have happened is there was no error checking and it silently failed. I am guessing when this happened it was a rule among many other rules and the rendered syntax was not looked at to see it rules you expected to be created were present.

If anyone feels this error still exists feel free to reopen the issue but please provide some clear information so I can reproduce the error.
