### ISSUE TITLE
cgrep.py object lookup (--obj/-o) is broken

### ISSUE THREAD

**Issue by fischa** [google/capirca#225]
I'm running Python 3.6.12 and...:
```
absl-py==0.11.0
capirca @ git+https://github.com/google/capirca@594fa8210c2d18a3b29620b9e86315c792fffc50
ipaddress==1.0.23
mock==4.0.2
ply==3.11
six==1.15.0
```
Due to the fact that cgrep.py was last touch 5 months ago I didn't check a later version of Capirca. Here is the example showing the problem:
```
python cgrep.py -o GOOGLE_DNS
I1201 12:46:03.639678 4562910656 cgrep.py:207] GOOGLE_DNS:
Traceback (most recent call last):
  File "cgrep.py", line 493, in <module>
    app.run(main, argv=sys.argv[:1])
  File "/Users/axel/git/net-acl/.venv/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/axel/git/net-acl/.venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "cgrep.py", line 209, in main
    ips.sort(key=lambda x: int(x.ip))
  File "cgrep.py", line 209, in <lambda>
    ips.sort(key=lambda x: int(x.ip))
AttributeError: 'IPv4' object has no attribute 'ip'
```

I couldn't find an attribute/function getting the required input to make the lambda function work except `x.network_address` but wasn't sure if there would be implications around this. So I've looked around and found nacaddr is offering a solution. Looks like https://github.com/google/capirca/blob/b3e605a54f12efa1e6b0b1cfd179ee6078313c9d/capirca/lib/nacaddr.py#L396 is doing what is needed:
```diff
# convert list of ip objects to strings and sort them
- ips.sort(key=lambda x: int(x.ip))
+ sorted_ips = nacaddr.SortAddrList(ips)
- p([str(x) for x in ips])
+ p([str(x) for x in sorted_ips])
```

This works as expected (sorted output):
```
python cgrep.py -o GOOGLE_DNS
I1201 12:46:48.040204 4400668096 cgrep.py:207] GOOGLE_DNS:
['8.8.4.4/32',
 '8.8.8.8/32',
 '2001:4860:4860::8844/128',
 '2001:4860:4860::8888/128']
I1201 12:46:48.040614 4400668096 cgrep.py:236]
````
cgrep_test.py doesn't catch that because it is testing get_nets only and doesn't do any sorting if I got that right (see https://github.com/google/capirca/blob/b3e605a54f12efa1e6b0b1cfd179ee6078313c9d/tests/lib/cgrep_test.py#L410).

If you want a PR for that let me know.

**Comment by fischa** [comment]
Any comment?

**Comment by greenpau** [comment]
@fischa , could you please retry with the latest version 2.0.3?

**Comment by fischa** [comment]
I will give it a try and get back to you.

**Comment by SecurityForDotes** [comment]
Just checking in to see if you had a chance to test it with the latest version

**Comment by fischa** [comment]
@greenpau + @SecurityForDotes
Ok - I've updated to Python 3.6.13 + capirca 2.0.3 and used cgrep.py that comes with this version (which isn't still the same cgrep.py I used in the earlier versions). No differences in error:
```
python ./.venv/lib/python3.6/site-packages/tools/cgrep.py -o GOOGLE_DNS
I0325 08:07:03.539216 4586048960 cgrep.py:207] GOOGLE_DNS:
Traceback (most recent call last):
  File "./.venv/lib/python3.6/site-packages/tools/cgrep.py", line 491, in <module>
    app.run(main, argv=sys.argv[:1])
  File "/Users/axel/git/net-acl/.venv/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/axel/git/net-acl/.venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./.venv/lib/python3.6/site-packages/tools/cgrep.py", line 209, in main
    ips.sort(key=lambda x: int(x.ip))
  File "./.venv/lib/python3.6/site-packages/tools/cgrep.py", line 209, in <lambda>
    ips.sort(key=lambda x: int(x.ip))
AttributeError: 'IPv4' object has no attribute 'ip'
```
So is the fix shown in my initial post something you would consider? Or how can I help moving forward?

**Comment by greenpau** [comment]
> So is the fix shown in my initial post something you would consider? Or how can I help moving forward?

@fischa , what would help here is creating a unit test for this.

**Comment by fischa** [comment]
Unfortunately I have no testing experience. But if you have a pointer for me how you would test the code snippet w/o writing the exact same code in the test - maybe it clicks and I can give it a try.
