### ISSUE TITLE
New PyPi release

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#240]
The current version of Capirca on [PyPi](https://pypi.org/project/capirca/) is from 2019, would it be possible to release a new one? Maybe at least match the Docker version (1.124).

Thanks.

**Comment by greenpau** [comment]
@XioNoX , this is currently being worked on. Will keep you posted.

**Comment by greenpau** [comment]
@XioNoX , this is now resolved. On a release of a new version, this actions will be triggered. https://github.com/google/capirca/commit/550622e6d57835429c0c92db64fe90c32c6ecacf
