### ISSUE TITLE
Attribute error : optimize 

### ISSUE THREAD

**Issue by chaitanya-jandhyam** [google/capirca#242]
I have following traceback if i start  --aclgen for my policies:

C:\Program Files\Capirca>python aclgen.py
I0222 16:20:32.837769  4080 aclgen.py:558] finding policies...
W0222 16:20:32.838766  4080 aclgen.py:467] --> ./policies/includes
W0222 16:20:32.839764  4080 aclgen.py:476] --> ./policies/includes (1 pol files found)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Capirca\aclgen.py", line 213, in RenderFile
    conf, definitions, optimize=FLAGS.optimize,
  File "C:\Python38\lib\site-packages\absl\flags\_flagvalues.py", line 480, in __getattr__
    raise AttributeError(name)
AttributeError: optimize
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aclgen.py", line 645, in <module>
    entry_point()
  File "aclgen.py", line 641, in entry_point
    app.run(main)
  File "C:\Python38\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Python38\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "aclgen.py", line 627, in main
    Run(
  File "aclgen.py", line 590, in Run
    result.get()
  File "C:\Python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
AttributeError: optimize

**Comment by greenpau** [comment]
@chaitanya-jandhyam , which target types the policy file refers to? i.e. which generator(s) are being used?

**Comment by chaitanya-jandhyam** [comment]
i didn't change anything , just running the sample policy files

**Comment by greenpau** [comment]
@chaitanya-jandhyam , how did you install capirca on Windows? `pip install` or `python3 setup.py install`?

**Comment by chaitanya-jandhyam** [comment]
python setup.py install

**Comment by chaitanya-jandhyam** [comment]
@greenpau any suggestions or any solution for my situation

**Comment by greenpau** [comment]
@chaitanya-jandhyam , I don’t know whether capirca is supported on windows. I would have to test.

meanwhile, try running it from a linux box.

**Comment by chaitanya-jandhyam** [comment]
ok , thanks for suggestion . i will try to work it on linux .

**Comment by greenpau** [comment]
@chaitanya-jandhyam , this is working on windows. I added Github Actions job for windows https://github.com/google/capirca/actions/runs/648090158 and it was successful.

**Comment by chaitanya-jandhyam** [comment]
Thank you
