### ISSUE TITLE
PAN generator rewrite questions

### ISSUE THREAD

**Issue by hkam40k** [google/capirca#243]
Hi,

I read in a commit yesterday that the PAN generator is being rewritten. Is there a schedule for when the new generator will replace the current one? Will it have feature-parity with current one? There are also a few PR's open for current PAN generator, any possibility for those changes (their concept) to be included in the rewrite?

Thanks.

**Comment by greenpau** [comment]
The core logic of PA generator is now complete.

**Comment by nero85** [comment]
Closing, this is complete.
