### ISSUE TITLE
Remove Id/Date/Revision from Juniper filter comment

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#247]
```
[edit firewall family inet]
+     /*
+      ** $Id:$
+      ** $Date:$
+      ** $Revision:$
+      **
+      */
```
All the Juniper filters I generate have those tags as comment at the beginning of the filter, is there a way to remove them?

Thanks

**Comment by fischa** [comment]
There is already an open issue (#217) and a PR associated with it. Feel free to join the conversation.

**Comment by rdsharma** [comment]
Duplicate of #217

**Comment by XioNoX** [comment]
Indeed, thanks!
