### ISSUE TITLE
Support multiple targets per header

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#257]
Based on https://github.com/google/capirca/wiki/Policy-format#header-section I was under the impression that a header could have multiple targets, for example:
```
header {
  target:: juniper testpol4 inet
  target:: juniper testpol6 inet6
}
term default {
    comment:: "test"
    action:: deny
}
```

But running that only outputs:
```
firewall {
    family inet {
        /*
         ** $Id:$
         ** $Date:$
         ** $Revision:$
         **
         */
        replace: filter testpol4 {
            interface-specific;
            /*
             ** test
             */
            term default {
                then {
                    discard;
                }
            }
        }
    }
}
```
While I would have expected both inet and inet6 filters to be generated.
I'm wondering if it's a regression, bug or was just never supported, but it would be nice to keep policy files as lean as possible.

The workaround is to do:
```
header {
  target:: juniper testpol4 inet
}
#include 'testpol.inc'

header {
  target:: juniper testpol6 inet6
}
#include 'testpol.inc'
```
Which is more complex and creates clutter.

What do you think?

Thanks.

**Comment by 991jo** [comment]
I dont think this is an issue specific to the juniper generator.
I have the same problem with the cisco generator.
Do all generators assume that there is only one target per generator per policy?
At least the cisco generator assumes this:
https://github.com/google/capirca/blob/master/capirca/lib/cisco.py#L934-L940

 and also the Header class in policy.py only returns values for the first target with a given name for the FilterOptions and FilterName methods:
https://github.com/google/capirca/blob/a9b76c79bcd6a6c3a22da14d9864066d1a3a7e3e/capirca/lib/policy.py#L1564-L1594

**Comment by XioNoX** [comment]
@greenpau see linked pull request, is that something you could review? Thanks
