### ISSUE TITLE
Paloalto generator should not mix TCP/UDP/ICMP protocols with pan-application

### ISSUE THREAD

**Issue by abhindes** [google/capirca#274]
When a term containing pan-application is used, it should not mix TCP/UDP protocols in the same rule. 
It should not mix this when TCP/UDP protocols are specified with a port, or without a port, or if ICMP/ICMPv6 is specified, or with ICMP types. Basically, pan-application should be used in a rule all by itself. 

An error should be raised when this happens. 

Some examples:

term test-4 {
  pan-application:: web-browsing
  protocol:: tcp
  action:: accept
}

term test-6 {
  pan-application:: ssl
  destination-port:: HTTPS MS_445
  protocol:: tcp
  action:: accept
}

**Comment by hkam40k** [comment]
Hello,

What is the reason to prevent using TCP/UDP with PA applications? It is not prevented by the platform either (unless something has changed recently?). On the PA platform, The PA applications have some default port defined, which if actually used, will work fine. But if wishing to use non-default ports, then a security rule can use a PA service in addition to the PA application. So preventing mixing TCP/UDP with applications does not make sense to me.

**Comment by abhindes** [comment]
This issue can be closed since this was fixed in #290 (which defined proper usage of pan-application) along with tests.
