### ISSUE TITLE
Incorrect IPv6 output for nftables 

### ISSUE THREAD

**Issue by afpd** [google/capirca#280]
Assume simple pol file

$ cat ./policies/pol/backup-server-inet6.pol
```
header {
  comment:: "nftables config for backup server"
  target:: nftables backup-server input 500 inet6
}

term accept-icmp {
  destination-address:: LINKLOCAL
  protocol:: icmpv6
  icmp-type:: echo-request echo-reply packet-too-big router-solicit router-advertisement neighbor-solicit neighbor-advertisement
  action:: accept
}
```

Resulting  backup-server-inet6.nft
 
```
flush table ip6 table_filter
table ip6 table_filter {
        chain backup-server {
                type filter hook input priority 500;
                ip daddr fe80::/10 icmp type { packet-too-big, echo-request, echo-reply, router-solicit, router-advertisement, neighbor-solicit, neighbor-advertisement} accept
        }
}
```

Unfortunately this is not a valid nftables config, ip instead of ip6, missing nexthdr and so on.
Problem exists for TCP as well.

**Comment by TheLinuxGuy** [comment]
We're currently working on making some changes to the nftables generator, we will keep this in mind.

This specific issue probably won't be looked at until after the rewrite of nftables.

**Comment by TheLinuxGuy** [comment]
Can you try the newnftables generator? https://github.com/google/capirca/commit/fcb2a08ac45426d4a4a569a30a6705ac1058f9ab

Rewrite is complete - note the HEADER options have changed. 

Here's your example with my new generator:
```
header {
  comment:: "https://github.com/google/capirca/issues/280"
  target:: newnftables inet6 INPUT
}

term accept-icmp {
  destination-address:: LINKLOCAL
  protocol:: icmpv6
  icmp-type:: echo-request echo-reply packet-too-big router-solicit router-advertisement neighbor-solicit neighbor-advertisement
  action:: accept
}

```

Output

```
table ip6 filtering_policies {
    chain accept-icmp {
        ip6 daddr fe80::/10 icmpv6 type { echo-request, echo-reply, packet-too-big, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } accept
    }
    chain root0 {
        comment "https://github.com/google/capirca/issues/280"
        type filter hook input priority 0; policy drop;
        jump accept-icmp
    }
}

```

I consider this fixed, can you confirm?

**Comment by afpd** [comment]
Much better now, thanks! However, there is still an issue.

```
flush table ip table_filter
table ip table_filter {
        chain backup-server {
                type filter hook input priority 500;
                ip protocol icmp counter accept
                ip saddr { 10.20.243.0/26, 10.98.145.2/32} tcp dport { 22, 80, 443, 6443} counter accept comment "Allow management requests from gtac-systems IPs." 
                ip saddr { 10.98.161.0/24, 10.6.12.0/24} tcp dport 22 counter accept comment "Allow to connect to backup server."  
                counter drop
        }
}
```

So if we run it for a first time on a system without any rules, we will get

`nft -c -f backup-server.nft`

```
 Error: No such file or directory; did you mean table ‘table_filter’ in family ip?
flush table ip table_filter
               ^^^^^^^^^^^^
```
However if there was table_filter  already, it works fine.

If there any conditional way to flush table on if one already exists?

**Comment by afpd** [comment]
Solution would be to create an empty table like this
```
table ip table_filter

flush table ip table_filter

table ip table_filter {
        chain backup-server { ...............
```
See https://unix.stackexchange.com/questions/537030/nftables-flush-delete-when-changing-or-creating-new-table

**Comment by TheLinuxGuy** [comment]
Thanks for the feedback. I was testing use a linux network namespace which is empty by default. 

I think the fix here is `nft flush ruleset` - let's try it. Take the .nft file from my https://github.com/google/capirca/commit/fcb2a08ac45426d4a4a569a30a6705ac1058f9ab that has the bug. On the first line above table add that line. Make sure you already had rules on your system. Now try to load the ruleset.

**Comment by TheLinuxGuy** [comment]
Where is `flush table ip table_filter` coming from in your https://github.com/google/capirca/issues/280#issuecomment-1129914511 - there is no code in newnftables.py that adds that pattern to the .nft file.

Can you attach **unedited the .nft that was generated by newnftables.py** and I will test locally on my box.

**Comment by afpd** [comment]
I use `aclgen` and capirca is from today's git
It produces for IPv6 from
```
header {
  comment:: "nftables config for backup server"
  target:: nftables backup-server input 500 inet6
}

term accept-icmp {
  destination-address:: LINKLOCAL
  protocol:: icmpv6
  icmp-type:: echo-request echo-reply packet-too-big router-solicit router-advertisement neighbor-solicit neighbor-advertisement
  action:: accept
}
```
file

```
flush table ip6 table_filter
table ip6 table_filter {
	chain backup-server {
		type filter hook input priority 500;
		ip daddr fe80::/10 icmp type { packet-too-big, echo-request, echo-reply, router-solicit, router-advertisement, neighbor-solicit, neighbor-advertisement} accept
	}
}
```

**Comment by TheLinuxGuy** [comment]
The .pol file you linked in https://github.com/google/capirca/issues/280#issuecomment-1130365511 is wrong.

Have you noticed the target header must be `target:: newnftables inet6 INPUT` - you are not testing my version until you change that... refer to my example in https://github.com/google/capirca/issues/280#issuecomment-1129583410 which is already edited for you....

**Comment by afpd** [comment]
HEAD is now at fcb2a08 NewNftables generator. Adds syslogging, counter and conntrack. Prepar  e for swap-in-place of the legacy nftables.py.
  
  `$ python3 setup.py install`      
  
  `$ cat policies/pol/backup-server-inet6.pol`
  ```
  header {
    comment:: "nftables config for backup server"
    target:: newnftables inet6 INPUT
  }
  
  term accept-icmp {
    destination-address:: LINKLOCAL
    protocol:: icmpv6
    icmp-type:: echo-request echo-reply packet-too-big router-solicit router-advertisement nei  ghbor-solicit neighbor-advertisement
    action:: accept
  }
  ```
  `aclgen` then produses no config at all

**Comment by TheLinuxGuy** [comment]
I found the issue; I'm unhiding some code blocks from our private repo that will enable this externally and sync it. Expect another commit in the next hour. Once its live; sync to master and re-run it.

```
/bin/aclgen --verbose --debug --base_directory ./policies --output_directory ./derp/ --recursive --optimize --definitions_directory ./def --logtostderr --policy_file ./policies/pol/sample_newnftables-mixed-icmp.pol
```

https://github.com/google/capirca/commit/8c9e66456fedb3c0fc1c641dbefc41793e5c68d5 is committed. Go ahead with testing this should work now.

**Comment by TheLinuxGuy** [comment]
I believe this issue to have be fixed.
