### ISSUE TITLE
Add support for generating prefix-list entries for juniper ACLs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/capirca#3]
```
prefix-list based ACLs in jcl's aren't much use if the prefix-list entries 
aren't automatically generated too.

This patch does that.
```

Original issue reported on code.google.com by `psarm...@gmail.com` on 15 Jan 2010 at 1:15

Attachments:
* [prefix-list.patch](https://storage.googleapis.com/google-code-attachments/capirca/issue-3/comment-0/prefix-list.patch)

**Comment by jejenone** [comment]
That would be a very interesting feature to be added - any chance to see this merged ?

**Comment by ankenyr** [comment]
Hi Jerome,
I believe we have this already this in our internal version. I am working really hard to get the external version up to par with the internal one. There are a couple of things internally I need to do but I should have things getting ready in the next week or two. Please stay tuned!

**Comment by ankenyr** [comment]
I believe this is now fixed. The lastest version of Capirca is now available for download and it should provide for prefix lists. I am marking this closed but feel free to reopen if this issue was not fixed.

**Comment by usagichan** [comment]
Is there an example of how this works for both juniper and srx filters? is there a new header setting we need to use similar to the "object-group" tag for cisco?  Otherwise I'm assuming source-prefix still expects a "text" entry.

Thanks

**Comment by ankenyr** [comment]
Ahh so yea you need to give it a string and currently it prints only that string.

I looked a bit closer at the patch and it seems that it is printing out the prefix-lists. The patch is nice but I think some stuff is being forgotten in the process. If I understand your desire correctly you want to give a definition like you would in source-address and have it populate a prefix list with the IPs from that definition?

The prefix lists in juniper can also use apply-path to create dynamic lists of IPs. Currently Capirca doesn't really have any logic to handle this and I know that it is a pretty commonly used feature.

My suggestion is this, we can accept this but there needs to be a target option to toggle the printing. The default action is to continue how it is today. If the option is given then it will create the prefix list with the appropriate IP addresses.

If someone wants to take this on I will be happy to reopen the issue.
