### ISSUE TITLE
Capirca overwrites the tools namespace

### ISSUE THREAD

**Issue by ankenyr** [google/capirca#323]
When using Capirca it will include the tools directory as a package. If Capirca was used in bazel as an external dependency this will clobber the existing namespace `tools` if it exists. This is unexpected for a Capirca to create namespaces outside of its own.

Capirca should either move tools into its own namespace
`from capirca.tools import cgrep`
or remove the tools from the package and add them as data files or something else.

**Comment by philsc** [comment]
This can be seen when you inspect the wheel from PyPI: https://pypi.org/project/capirca/#files
```console
$ curl -LO 'https://files.pythonhosted.org/packages/cc/31/5fa4f85c8b0d48162deced86d441c5b25f2ae4491d5053144e2557636330/capirca-2.0.6-py3-none-any.whl'
$ unzip -v capirca-2.0.6-py3-none-any.whl
...
    1843  Defl:N      642  65% 2022-06-15 19:34 2ccd34f4  capirca/utils/config.py
    3172  Defl:N      885  72% 2022-06-15 19:34 1f350276  capirca/utils/iputils.py
       0  Defl:N        2   0% 2022-06-15 19:34 00000000  tools/__init__.py
   15337  Defl:N     4605  70% 2022-06-15 19:34 1fd8fdd1  tools/cgrep.py
    1918  Defl:N      770  60% 2022-06-15 19:34 dc87acbf  tools/iputilstools.py
     319  Defl:N      209  35% 2022-06-15 19:34 631ead1b  capirca-2.0.6.dist-info/AUTHORS
   11358  Defl:N     3949  65% 2022-06-15 19:34 86e2b4b4  capirca-2.0.6.dist-info/LICENSE
...
```
I.e. the 3 files in the top-level `tools` directory are creating a new top-level `tools` module which easily interferes with other things.
