### ISSUE TITLE
Add principals optional keyword

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/capirca#33]
```
Purpose of code changes on this branch:
Add 'principals' optional keyword to policy.py. This is intended to allow a 
policy author to include this in a term when an ACL involves a list of named 
groups.

After the review, I'll merge this branch into:
/trunk


```

Original issue reported on code.google.com by `pne...@google.com` on 20 Dec 2012 at 5:08

Attachments:
* [policydiff](https://storage.googleapis.com/google-code-attachments/capirca/issue-33/comment-0/policydiff)

**Comment by ankenyr** [comment]
I believe this is already pulled in. Will be closing this.
