### ISSUE TITLE
Patch for /trunk/def/NETWORK.net

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/capirca#34]
```
192.18/15 should be 198.18/15 according to team-cymru.org and other sources.  
192.18/15 appears in public routing tables and shows assignments from 
registries.
```

Original issue reported on code.google.com by `br...@dropbox.com` on 28 Aug 2014 at 6:54

Attachments:
* [NETWORK.net.patch](https://storage.googleapis.com/google-code-attachments/capirca/issue-34/comment-0/NETWORK.net.patch)

**Comment by ankenyr** [comment]
This was fixed ages ago.
