### ISSUE TITLE
Patch for /trunk/lib/junipersrx.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/capirca#35]
```
This patch adds support of global policies and address book on Juniper SRXs.

I tried to do it the cleanest way possible, please let me know how I can 
improve it if needed.

To use it add the keyword "global_address_book" to the target line in _all_ 
your headers (as you can't have both per zone and global address-book).

header {
  comment:: "Generated by Capirca"
  target:: srx from-zone corp to-zone vpn global_address_book
}

If you need to add the "global { }" policies block do:

header {
  comment:: "Generated by Capirca"
  target:: srx from-zone global_policies to-zone global_policies global_address_book
}

Thanks!

```

Original issue reported on code.google.com by `xionox` on 30 Oct 2014 at 1:35

Attachments:
- [junipersrx.py.patch](https://storage.googleapis.com/google-code-attachments/capirca/issue-35/comment-0/junipersrx.py.patch)

**Comment by XioNoX** [comment]
That's mine, please let me know if I can help.

**Comment by ankenyr** [comment]
Hi XioNoX!
I think you also expressed interest in #3 ? If so that is fixed also with my latest massive update! I hope you like it.
I believe the latest srx has a global address book. I would need to check our own commits. Can you let me know if that fixed the issue for you?

**Comment by XioNoX** [comment]
The lastest SRX does support properly global address book as well as global security zones.
Thank you

**Comment by ankenyr** [comment]
I believe in our conversation over IRC you said this was no longer applicable. Marking as closed. Please reopen if I am wrong!
