### ISSUE TITLE
_GetParents does not account for comments

### ISSUE THREAD

**Issue by GoodEveningMiss** [google/capirca#46]
https://github.com/google/capirca/blob/master/lib/naming.py#L213

All the other methods to retrieve or search for tokens strip off any potential comments and whitespace before making any comparison. _GetParents does not. Library could be improved in general by stripping off comments when parsing and saving it as its own attribute.

**Comment by GoodEveningMiss** [comment]
Also in GetIpParents:
https://github.com/google/capirca/blob/master/lib/naming.py#L173

**Comment by ankenyr** [comment]
This was in the last  push d10959d20f732c224e0f7d8e568d435f1b2cd8e8
