### ISSUE TITLE
Packaging of Capirca libraries

### ISSUE THREAD

**Issue by ankenyr** [google/capirca#59]
Noticed this thread back from 2013 on the old capirca-dev google group.
https://groups.google.com/forum/#!topic/capirca-dev/mGls2XFH7ug

This is a good idea I believe.
Having a directory structure look something like the following
capirca/
capirca/generators/<cisco/juniper/...>
capirca/naming.py
capirca/policy.py

I understand there is work on new policy parsers. Those could live in a new directory called capirca/parsers.

Like it is said in the thread aclgen.py would be a script.

**Comment by jzohrab** [comment]
Makes sense.  This is a very big change and is going to cause many conflicts between your code and anyone actively doing development (aka, me!).  Can you hold off on this until we try to merge our codebases?

Any front-facing script (like aclgen.py) should only work with primitives, and not expose domain objects.  That was one of the changes I did in aclgen.py - created an AclGen domain object (which is like a "Service" pattern).

**Comment by ankenyr** [comment]
I agree on waiting. I know the big push that I will make soon will be a huge pain for all of us. Again, happy to help as much as possible. Your changes, specifically the yaml stuff, are great and I think the community would love it.

I made this just to keep track of the issue and I am considering closing the google group capirca-dev as I don't see why we should be looking at two places for community communication.

Can you clarify your second paragraph?

**Comment by jzohrab** [comment]
Yeah, the google group seems to be dead.

For the second paragraph: I wanted to use some of the methods in aclgen.py from a script, which seemed reasonable.  The methods, though, took a lib.naming.Naming object as a parameter, which meant that external clients would have to populate the object and send it in as well.  I figured that the script should be a true script, meaning that it would only contain things like numbers, strings, and maybe hashes.  So, I changed that script to have a small API (just a few methods) and delegated the rest to a Service object, the new AclGen class.

Re "Service" pattern - this is a handy term from "Domain Driven Design" by Eric Evans.  The idea is that the domain is made up of classes, but ultimately something has to actually coordinate all of these things to do something useful.  Usually that's too much for a class to handle, and so something at a higher level does the coordination.  https://lostechies.com/jimmybogard/2008/08/21/services-in-domain-driven-design/ is a good link.

**Comment by jzohrab** [comment]
ps - for Parsers, I've been thinking that the Naming class could also have a simpler YAML-based equivalent.  I won't touch that until I've added characterization tests for that as well (that is, tests to ensure that existing behaviour is not broken).

**Comment by ankenyr** [comment]
Closing, looking back on this I am not sure what the reorganization would buy us. I don't feel we have enough in lib to really warrant this restructuring considering the hassle that moving the tests directory was.
