### ISSUE TITLE
migrate away from mox towards mock

### ISSUE THREAD

**Issue by finfinack** [google/capirca#61]
We should be moving away from using mox as a unit test framework and instead rewrite them to use mock (https://docs.python.org/3/library/unittest.mock.html). The unit tests based on mock are easier to read and write and gets rid of the "record functionality / replay" weirdness.

If there's consensus we want to migrate away from mox, I'm happy to start but I didn't want to invest time unless we agree it makes sense...

Thoughts?

**Comment by ankenyr** [comment]
I agree with this. I was planing on doing rewrites little by little. If you have time to do some please feel free.

**Comment by finfinack** [comment]
Sgtm. I don't think there's a hurry but I saw the word "mox" fly by in another post of yours and that reminded me :) I won't promise anything but same as you, I'd plan for migrating little by little.

**Comment by finfinack** [comment]
FWIW, I started the migration with commit https://github.com/google/capirca/commit/ef1a05917f8445d82c77002cc416227e4d992d84 - let me know how that works for you (works fine here but my home setup is somewhat special...).

**Comment by finfinack** [comment]
Had some time to migrate the rest of the unittests over as well. Should all be done now and I removed mox from setup.py.

$ python2.7 -m unittest discover -s . -p '*_test.py'
[snip]
----------------------------------------------------------------------
Ran 435 tests in 34.703s

OK
