### ISSUE TITLE
SRX security zone VPN not accepted

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#62]
I'm testing your latest commits with my policies.

The policies containing for example:
"target:: srx from-zone corp to-zone vpn"
fail because of the vpn zone:
```
Traceback (most recent call last):
  File "aclgen.py", line 498, in <module>
    main(FLAGS(sys.argv))
  File "aclgen.py", line 461, in main
    FLAGS.exp_info, write_files)
  File "aclgen.py", line 193, in RenderFile
    input_file, sys.exc_info()[0], sys.exc_info()[1]))
__main__.ACLParserError: Error parsing policy file policies/pol/offices_srx_base_policies-global.pol:
<class 'lib.policy.ParseError'> ERROR on "vpn" (type VPN, line 262, Next '}')
```
If I rename vpn into something else it then works fine.

**Comment by ankenyr** [comment]
I believe I see the problem. vpn is a option inside of terms.
Try changing it to vpn_s and it works, then try changing it to something else that is a term option like comment and it breaks.

I will need to explore the parsers a bit to see if there is a way to search for begining of lines.

In the mean time you can easily get around this by renaming it from vpn to something like vpn_zone or remote_access or some other name besides "vpn"
