### ISSUE TITLE
Unclear how to test with new 'gflags' module

### ISSUE THREAD

**Issue by jzohrab** [google/capirca#66]
The code has changed from using optparse to google's gflags, and I'm not sure how to test with that.

In my development branch (which I'm trying to fix in branch merge_master so I can submit a PR back to google capirca master, ref https://github.com/jzohrab/capirca/commits/merge_master), I have a few tests to do sanity checks at an integration level.  The tests have lines such as the following:

```
  def test_generate_single_policy(self):
    aclgen.main(['-p', 'policies/sample_cisco_lab.pol'])
```

aclgen.py now has FLAGS which are defined as follows:
```
FLAGS = flags.FLAGS
flags.DEFINE_string(
    'base_directory',
    '.',
    'The base directory to look for acls; '
    'typically where you\'d find ./corp and ./prod')
... etc
```

are these specified on command line as e.g., `python aclgen.py --base_directory /path/to/files`?  I ask because the tests seem to run ... though I don't think they should ... even without specifying `--base_directory`.  I can't find docs on how gflags are to be used, pls point me in the right direction.

I have a few other issues with the merge, if someone on the team can spare time for a short conference cal that would be great.  Thanks!

**Comment by ankenyr** [comment]
flags will parse things from the command line.
That is exactly what it is doing on here https://github.com/google/capirca/blob/master/aclgen.py#L498

For an integration test like this you can pass in new arguments. I made a copy of your code and changed things around a bit, here is what I changed.

```
  def test_generate_single_policy(self):
    import pdb;pdb.set_trace()
    aclgen.main(['-p', 'policies/foobar.pol'])

    expected_output = """writing ./filters/sample_cisco_lab.acl
1 filters rendered
"""
    self.assertEquals(expected_output, self.iobuff.getvalue())
```

and dropping into a debugger to explore a bit we can see the effect

```
$ python test_aclgen.py 
E..EEEE.EE........> /usr/local/google/home/robankeny/Desktop/jz_caprica/capirca/test_aclgen.py(67)test_generate_single_policy()
-> aclgen.main(['-p', 'policies/foobar.pol'])
(Pdb) s
--Call--
> /usr/local/google/home/robankeny/Desktop/jz_caprica/capirca/aclgen.py(352)main()
-> def main(args):
(Pdb) n
> /usr/local/google/home/robankeny/Desktop/jz_caprica/capirca/aclgen.py(353)main()
-> FLAGS = parse_args(args)
(Pdb) n
> /usr/local/google/home/robankeny/Desktop/jz_caprica/capirca/aclgen.py(355)main()
-> gen = AclGen(policy_directory = FLAGS.policy_directory,
(Pdb) print FLAGS
{'policy_format': 'capirca', 'exp_info': 2, 'output_directory': './filters', 'debug': False, 'policy_directory': False, 'policy': 'policies/foobar.pol', 'definitions': './def', 'shade_check': False}

```


For unittests where flags are not parsed but expected to be present already you will want to use mock to mock out the object. I cannot think of any examples off the top of my head that are available at this very moment because the generators don't use flags I believe.

Let me know if that answers all your questions!

**Comment by jzohrab** [comment]
Hello @ankenyr, thanks for taking the time.

One thing I still can't follow is the relationship between `aclgen.main(['-p', 'policies/foobar.pol'])` and how that actually gets translated to `'policy': 'policies/foobar.pol'`.  aclgen.py has `FLAGS = flags.FLAGS`, which has a line like below:

```
flags.DEFINE_string(
    'policy_file',
    None,
    'Individual policy file to generate.')
```

Unlike optparse, there is no "short form" and "long form" for a given option, so I'm not sure how gflags determines that `-p` really means `policy_file`.  Does it do an intelligent guess, based on first letter?  If so, how would it distinguish between `output_directory` and `optimize`, both of which are other options?

fyi for the unit testing, I'm not mocking the code, instead I propose a very small change to aclgen as follows:

```
def main(args):
  FLAGS(args)
  ... snip ...

if __name__ == '__main__':
  # Start main program.
  # Pass in command-line args.
  main(sys.argv)
```

That lets me call main() and pass in args at runtime with no mocking hassles.  That's what I did with my old closed pull req

**Comment by ankenyr** [comment]
Ok so i misspoke sorta. The version I downloaded was your main branch, not your integration one. Weird thing is I don't see things passing in there.
So flags as I understand it is a global, I looked back at some old code where I needed to do this. The recommendation was something like the following

```
<snip>
import gflags as flags

FLAGS = flags.FLAGS

class Test_AclGen(unittest.TestCase):
<snip>
  def test_generate_single_policy(self):
    FLAGS.policy_file = './policy/pol/sample_cisco_lab.pol'
    aclgen.main([])

```

I was able to get the tests passing using that, if you are using a default flag you don't need to set it. You can move these into the setup function too.

**Comment by jzohrab** [comment]
Ok, will give that a shot.  The gflags documentation and source is sparse on how to actually use it.  Thank you, will report back later.

**Comment by jzohrab** [comment]
Got the test running with the following:

```
    args = [
      'program',  # Dummy value for gflags, which expects the program name to be the first entry.
      '--base_directory={0}'.format(pol_dir),
      '--definitions_directory={0}'.format(def_dir),
      '--output_directory={0}'.format(self.output_dir)
    ]
    aclgen.main(args)
```

I prefer to pass in the actual args, keeping this as black-box testing rather than touching the internals.  There's a small wart with the dummy first flag, but otherwise this works and tests things at the top level, which is a good overall check for the project as a whole.

Thanks @ankenyr.
