### ISSUE TITLE
Potential global state trouble with policy.py's _OPTIMIZE flag

### ISSUE THREAD

**Issue by jzohrab** [google/capirca#70]
policy.py has the following in TranslateTerms():

```
    for term in terms:
      ...
      term.AddressCleanup(_OPTIMIZE)
      # Reset _OPTIMIZE global to default value
      globals()['_OPTIMIZE'] = True
      term.SanityCheck()
      term.translated = True
```

_OPTIMIZE could be set to False globally at the start of an aclgen run, but when TranslateTerms is called with a policy with multiple terms, it will be False for the first term, and then True for all remaining terms.

I don't have a test case illustrating this behaviour yet, but it shouldn't be hard to come up with one.

I don't know if the global _OPTIMIZE setting will influence multiple policies.  I'll need to look further into what the implications for this are.

At any rate, global state is bad, and the current changing of global state during the run feels incorrect.

**Comment by jzohrab** [comment]
Same issue with _SHADE_CHECK, which is set at a global level but then potentially overridden with a call in policy.py:

```
  def _DetectShading(self, terms):
    ...
    globals()['_SHADE_CHECK'] = False
```

Because of this global state, the test `python -m unittest tests.lib.policy_test.PolicyTest.testTermEquality` was passing when it was run on its own, but failing when run as part of the full test suite.  At least, that's my initial hypothesis, I didn't have time to investigate fully.

**Comment by GoodEveningMiss** [comment]
seconded, saw this with _OPTIMIZE and _SHADE_CHECK

**Comment by sjtarik** [comment]
This is still an issue. Just for consistent behavior, I suggest setting FLAGS.optimize default value to True and removing the statement pointed out by @jzohrab.

**Comment by ankenyr** [comment]
This should be fixed as of a few pushes ago
