### ISSUE TITLE
naming.NoDefinitionsError swallowed in aclgen.py

### ISSUE THREAD

**Issue by jzohrab** [google/capirca#77]
aclgen.py has the following if there is a bad def’s directory:

```
  except naming.NoDefinitionsError:
    logging.fatal('bad definitions directory: %s', FLAGS.definitions_directory)
```

However, the error is swallowed and the program continues.

**Comment by pw378** [comment]
Verified.

$ python ./aclgen.py --definitions_directory=/foo
CRITICAL:root:bad definitions directory: /foo
WARNING:root:--> ./policies/includes
WARNING:root:--> ./policies/includes (0 pol files found)
WARNING:root:WARNING:...
<<snip>>

Proposed fix:
https://github.com/google/capirca/pull/142

**Comment by ankenyr** [comment]
Thanks for the work @pw378
