### ISSUE TITLE
dst ports automatically added to established term

### ISSUE THREAD

**Issue by ryantierney513** [google/capirca#86]
aclgenerator (via FixHighPorts) automatically appends destination-ports 1024-65535 to the rendered term if option:: established is set.
This can cause unwanted filtering behavior if the user intentionally left off destination-port or only wants it to be a port or port range below 1024.

There may be cases where users or platforms expect or desire this behavior, but I don't believe this should be the default. Perhaps FixHighPorts should be disabled by default and can be re-enabled via a new header option?

Example policy:

```
header {
    comment:: "testing tcp established"
    target:: juniper test-filter inet not-interface-specific
}

term allow-tcp-established {
    protocol:: tcp
    option:: established
    counter:: allow.tcp.established
    action:: accept
}
```

Rendered config:

```
firewall {
    family inet {
        replace:
        /*
        ** $Id:$
        ** $Date:$
        ** $Revision:$
        **
        ** testing tcp established
        */
        filter test-filter {
            term allow-tcp-established {
                from {
                    protocol tcp;
                    destination-port 1024-65535;
                    tcp-established;
                }
                then {
                    count allow.tcp.established;
                    accept;
                }
            }
        }
    }
}
```

**Comment by ankenyr** [comment]
I feel this is working as intended. If the user wants a specific port then they would need to set it in the term which should override the use of high ports as a default. If they leave it off then what was their intention? It seems weird to me to leave high ports off.

Can you give an example where someone would leave ports off their term and the inclusion of high ports would conflict with their intent?

**Comment by ryantierney513** [comment]
The biggest problem I see is that the value isn't overrideable. Even if I define a specific destination-port in that term, it still automatically adds 1024-65535:

```
header {
    comment:: "testing tcp established"
    target:: juniper test-filter inet not-interface-specific
}

term allow-tcp-established {
    destination-port:: WEB_SERVICES
    protocol:: tcp
    option:: established
    counter:: allow.tcp.established
    action:: accept
}
```

```
firewall {
    family inet {
        replace:
        /*
        ** $Id:$
        ** $Date:$
        ** $Revision:$
        **
        ** testing tcp established
        */
        filter test-filter {
            term allow-tcp-established {
                from {
                    protocol tcp;
                    destination-port [ 80 443 1024-65535 ];
                    tcp-established;
                }
                then {
                    count allow.tcp.established;
                    accept;
                }
            }
        }
    }
}
```

Even if I specify a port that's within 1024-65535 in an effort to override that value, it still produces 1024-65535:

```
header {
    comment:: "testing tcp established"
    target:: juniper test-filter inet not-interface-specific
}

term allow-tcp-established {
    destination-port:: WEB_SERVICES MYSQL
    protocol:: tcp
    option:: established
    counter:: allow.tcp.established
    action:: accept
}

```
```
firewall {
    family inet {
        replace:
        /*
        ** $Id:$
        ** $Date:$
        ** $Revision:$
        **
        ** testing tcp established
        */
        filter test-filter {
            term allow-tcp-established {
                from {
                    protocol tcp;
                    destination-port [ 80 443 1024-65535 ];
                    tcp-established;
                }
                then {
                    count allow.tcp.established;
                    accept;
                }
            }
        }
    }
}
```

This then becomes a problem if someone only wants a small subset of ports to receive the established traffic rather than >1023. Admittedly, there aren't a _ton_ of use cases where a host or application will select a source-port <1024 when creating the socket and therefore not want >1023 as a destination-port in the return traffic filter, but there's no telling what the needs of others' hosts and/or applications will be.

I think defaulting to 1024-65535 is OK if no destination-port token is provided, but if one is provided, only the given ports should be included in the term.

**Comment by djinh** [comment]
Fully agree that always adding 1024-65535 is wrong :)

If I omit the destination-port token, I would not expect it to appear in the config as 1024-65535 though.

**Comment by ankenyr** [comment]
So there are two established that are supported

Copied from out wiki

> established - only match established connections, implements tcp-established for tcp and sets destination port to 1024- 65535 for udp if destination port is not defined.
tcp-established - only match established tcp connections, based on statefull match or TCP flags. Not supported for other protocols.

so I tried testing things just now with the following term for fun

```
header {
  target:: juniper edge-inbound inet
}

term permit-web-server-requests {
  destination-address:: WEB_SERVERS
  protocol:: tcp
  destination-port:: WEB_SERVICES
  action:: accept
}

header {
  target:: juniper edge-outbound
}

term permit-web-server-replies {
  source-address:: WEB_SERVERS
  destination-port:: DNS
  protocol:: tcp
  option:: <tcp-established|established>
  action:: accept
}
```


with `tcp-established` I got 


```
protocol tcp;
destination-port 53;
tcp-established;
```

with `established` you get

```
protocol tcp;
destination-port [ 53 1024-65535 ];
tcp-established;
```

However if I was to substitute the protocol for UDP the results end up being the following

`established` results in

```
protocol udp;
destination-port 1024-65535;
```

`tcp-established` results in an TCPEstablishedWithNonTcp Error.

There is a difference between the two established options. In the case above @ryantierney513 I feel if you were to use the tcp-established option instead you would get your desired results. If I am wrong please let me know. Same goes for you @djinh. If you both feel strongly that this is incorrect lets continue the discussion. If this was simply an error of not knowing about the differences between tcp-established and established let me know how I could make this clearer. Maybe fixing up the wiki?

**Comment by djinh** [comment]
A couple reasons why I think this is very confusing behavior:

1. 'Established' traditionally means ACK or RST flag set in the TCP header and has no meaning for UDP.
2. Having the 'established' keyword do two wildly different things, depending on if we're in a UDP or TCP context, seems very counterintuitive to me.
3. The 1024-65535 port range is only special because the default configuration on unix-based systems allow processes not running as root to use those. I'm not sure why that range should be associated with the keyword 'established', which traditionally refers to something else.

JunOS itself only has the 'tcp-established' keyword. The most intuitive thing for me would be to:

1. Throw an error is either established or tcp-established is used in a UDP context;
2. Make the two options equivalent to each other and have them both render to 'tcp-established' on JunOS when used in a TCP context.

I'm not sure if this would be a major change though, given that the other behavior is documented.

**Comment by ankenyr** [comment]
The tl;dr is use tcp-established with tcp, established with udp.

established is a concept for UDP in stateful firewalls. We can look at an example for iptables.

```
header {
  target:: iptables INPUT
}
term term-one {
  destination-address:: GOOGLE_DNS
  destination-port:: DNS
  protocol:: udp
  action:: accept
}
header {
  target:: iptables OUTPUT
}
term replies-one {
  source-address:: GOOGLE_DNS
  destination-port:: HIGH_PORTS
  protocol:: udp
  action:: accept
}
term replies-two {
  source-address:: GOOGLE_DNS
  protocol::udp
  option:: established
  action:: accept
}
```
The output from this looks like the following.

```
# Iptables INPUT Policy
# $Id:$
# $Date:$
# $Revision:$
# inet
-N I_term-one
-A INPUT -j I_term-one
-A I_term-one -p udp --dport 53 -d 8.8.4.4/32 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
-A I_term-one -p udp --dport 53 -d 8.8.8.8/32 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
# Iptables OUTPUT Policy
# $Id:$
# $Date:$
# $Revision:$
# inet
-N O_replies-one
-A OUTPUT -j O_replies-one
-A O_replies-one -p udp --dport 1024:65535 -s 8.8.4.4/32 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
-A O_replies-one -p udp --dport 1024:65535 -s 8.8.8.8/32 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
-N O_replies-two
-A OUTPUT -j O_replies-two
-A O_replies-two -p udp --dport 1024:65535 -s 8.8.4.4/32 -m state --state ESTABLISHED,RELATED -j ACCEPT
-A O_replies-two -p udp --dport 1024:65535 -s 8.8.8.8/32 -m state --state ESTABLISHED,RELATED -j ACCEPT
```

Which one of the replies is correct?

**Comment by ankenyr** [comment]
I am going to mark this as closed since there has been no further discussion. Please feel free to reopen.
