### ISSUE TITLE
Update cgrep to use logging instead of print.

### ISSUE THREAD

**Issue by ankenyr** [google/capirca#87]
Please see https://github.com/google/capirca/pull/79#discussion_r67462242 for more discussion.
cgrep currently uses print when it really should use logging. Lets fix this at some point. If someone wants to take this up let me know here and I can assign it to you.

**Comment by sneakywombat** [comment]
@ryantierney513 any interest in this?

**Comment by ankenyr** [comment]
Fixed this in 7a30987fb5e6b24a72625a8f1830109dbdb1a26d
