### ISSUE TITLE
Cisco ACL summarization problem

### ISSUE THREAD

**Issue by Swanfir** [google/capirca#89]
Hi together,

I have a strange behavior with generated CISCO ACL summarization of entries.

The first term in the .pol file is not summarized in the .acl file. A copy, rename and place the copy right behind the original term is working for the copy. Deleting  one of the terms bring back the no summarization thing. Even a summarized term is not summarized if it get the first position.

Version: Downloaded for two weeks ago from here

Thanks in advance
Swanfir

**Comment by ankenyr** [comment]
Can you provide me with more information so I can reproduce this? Possibly making a simple .pol and .net file that I could run and see the problem?

**Comment by Swanfir** [comment]
I try to reproduce it in an other environment over weekend to be sure it is not my setup. And come back with information on Monday.

**Comment by Swanfir** [comment]
so the same picture here.
What I did, get a clone and leave all as it is as default. At the end of the .net file added  LAB IPS:

##LAB
IP1	 =	192.168.81.0
IP2	 =	192.168.81.1
IP3	 =	192.168.81.2
IP4	 =	192.168.81.3
IP5	 =	192.168.81.4
IP6	 =	192.168.81.5
IP7	 =	192.168.81.6
.
.
.
IP256	 =	192.168.81.255

Create a group 
LABNET = IP12
	IP13
	IP14
	IP15
	.
	.
	.
	IP31

My .pol look like this:
header {
 comment:: "LAB"
 target:: cisco Lab extended
}

term permit-PING {
 destination-address:: IP3
 icmp-type:: echo-request echo-reply unreachable
 protocol:: icmp
 source-address:: LABNET
 action:: accept
}

term permit-PING2 {
 destination-address:: IP3
 icmp-type:: echo-request echo-reply unreachable
 protocol:: icmp
 source-address:: LABNET
 action:: accept
}

term default-deny{
 action:: deny
}

Resulting  .acl

remark permit-PING
 permit 1 host 192.168.81.11 host 192.168.81.2 0
 permit 1 host 192.168.81.11 host 192.168.81.2 3
 permit 1 host 192.168.81.11 host 192.168.81.2 8
 permit 1 host 192.168.81.12 host 192.168.81.2 0
 permit 1 host 192.168.81.12 host 192.168.81.2 3
 permit 1 host 192.168.81.12 host 192.168.81.2 8
 permit 1 host 192.168.81.13 host 192.168.81.2 0
 permit 1 host 192.168.81.13 host 192.168.81.2 3
 permit 1 host 192.168.81.13 host 192.168.81.2 8
 permit 1 host 192.168.81.14 host 192.168.81.2 0
 permit 1 host 192.168.81.14 host 192.168.81.2 3
 permit 1 host 192.168.81.14 host 192.168.81.2 8
 permit 1 host 192.168.81.15 host 192.168.81.2 0
 permit 1 host 192.168.81.15 host 192.168.81.2 3
 permit 1 host 192.168.81.15 host 192.168.81.2 8
 permit 1 host 192.168.81.16 host 192.168.81.2 0
 permit 1 host 192.168.81.16 host 192.168.81.2 3
 permit 1 host 192.168.81.16 host 192.168.81.2 8
 permit 1 host 192.168.81.17 host 192.168.81.2 0
 permit 1 host 192.168.81.17 host 192.168.81.2 3
 permit 1 host 192.168.81.17 host 192.168.81.2 8
 permit 1 host 192.168.81.18 host 192.168.81.2 0
 permit 1 host 192.168.81.18 host 192.168.81.2 3
 permit 1 host 192.168.81.18 host 192.168.81.2 8
 permit 1 host 192.168.81.19 host 192.168.81.2 0
 permit 1 host 192.168.81.19 host 192.168.81.2 3
 permit 1 host 192.168.81.19 host 192.168.81.2 8
 permit 1 host 192.168.81.20 host 192.168.81.2 0
 permit 1 host 192.168.81.20 host 192.168.81.2 3
 permit 1 host 192.168.81.20 host 192.168.81.2 8
 permit 1 host 192.168.81.21 host 192.168.81.2 0
 permit 1 host 192.168.81.21 host 192.168.81.2 3
 permit 1 host 192.168.81.21 host 192.168.81.2 8
 permit 1 host 192.168.81.22 host 192.168.81.2 0
 permit 1 host 192.168.81.22 host 192.168.81.2 3
 permit 1 host 192.168.81.22 host 192.168.81.2 8
 permit 1 host 192.168.81.23 host 192.168.81.2 0
 permit 1 host 192.168.81.23 host 192.168.81.2 3
 permit 1 host 192.168.81.23 host 192.168.81.2 8
 permit 1 host 192.168.81.24 host 192.168.81.2 0
 permit 1 host 192.168.81.24 host 192.168.81.2 3
 permit 1 host 192.168.81.24 host 192.168.81.2 8
 permit 1 host 192.168.81.25 host 192.168.81.2 0
 permit 1 host 192.168.81.25 host 192.168.81.2 3
 permit 1 host 192.168.81.25 host 192.168.81.2 8
 permit 1 host 192.168.81.26 host 192.168.81.2 0
 permit 1 host 192.168.81.26 host 192.168.81.2 3
 permit 1 host 192.168.81.26 host 192.168.81.2 8
 permit 1 host 192.168.81.27 host 192.168.81.2 0
 permit 1 host 192.168.81.27 host 192.168.81.2 3
 permit 1 host 192.168.81.27 host 192.168.81.2 8
 permit 1 host 192.168.81.28 host 192.168.81.2 0
 permit 1 host 192.168.81.28 host 192.168.81.2 3
 permit 1 host 192.168.81.28 host 192.168.81.2 8
 permit 1 host 192.168.81.29 host 192.168.81.2 0
 permit 1 host 192.168.81.29 host 192.168.81.2 3
 permit 1 host 192.168.81.29 host 192.168.81.2 8
 permit 1 host 192.168.81.30 host 192.168.81.2 0
 permit 1 host 192.168.81.30 host 192.168.81.2 3
 permit 1 host 192.168.81.30 host 192.168.81.2 8

remark permit-PING2
 permit 1 host 192.168.81.11 host 192.168.81.2 0
 permit 1 host 192.168.81.11 host 192.168.81.2 3
 permit 1 host 192.168.81.11 host 192.168.81.2 8
 permit 1 192.168.81.12 0.0.0.3 host 192.168.81.2 0
 permit 1 192.168.81.12 0.0.0.3 host 192.168.81.2 3
 permit 1 192.168.81.12 0.0.0.3 host 192.168.81.2 8
 permit 1 192.168.81.16 0.0.0.7 host 192.168.81.2 0
 permit 1 192.168.81.16 0.0.0.7 host 192.168.81.2 3
 permit 1 192.168.81.16 0.0.0.7 host 192.168.81.2 8
 permit 1 192.168.81.24 0.0.0.3 host 192.168.81.2 0
 permit 1 192.168.81.24 0.0.0.3 host 192.168.81.2 3
 permit 1 192.168.81.24 0.0.0.3 host 192.168.81.2 8
 permit 1 192.168.81.28 0.0.0.1 host 192.168.81.2 0
 permit 1 192.168.81.28 0.0.0.1 host 192.168.81.2 3
 permit 1 192.168.81.28 0.0.0.1 host 192.168.81.2 8
 permit 1 host 192.168.81.30 host 192.168.81.2 0
 permit 1 host 192.168.81.30 host 192.168.81.2 3
 permit 1 host 192.168.81.30 host 192.168.81.2 8

remark default-deny
 deny ip any any

Hopefully that will help.

**Comment by ankenyr** [comment]
I have not tested this out yet but are you expecting me to fill out each definition between IP7 through IP256 and IP15 through IP31?

**Comment by ankenyr** [comment]
Going to close this because of no response soon.

I am not going to type in 200+ lines. You need to provide me with files (or their full content) to reproduce this or find a more succinct set of IPs that reproduces this error.
