### ISSUE TITLE
cgrep get_services function doesn't respect protocol when comparing against a range

### ISSUE THREAD

**Issue by ryantierney513** [google/capirca#92]
PPP class __contains__ function ignored protocol when comparing one PPP object against a port range.

This leads to a condition where cgrep would incorrectly return a service object that doesn't contain the protocol which was passed into cgrep.

Example:

```
~] cat BLAH.svc 
TCP_80 = 80/tcp
UDP_80 = 80/udp
UDP_1-65535 = 1-65535/udp

~] python cgrep.py -p 80 tcp -d ~/
80/tcp:
['TCP_80',
 'UDP_1-65535']
```

80/tcp is obviously not within 1-65535/udp

I already have a fix for this internally and will start the process of getting a PR published.

**Comment by ankenyr** [comment]
Thanks for finding that and for the coming PR!

**Comment by ryantierney513** [comment]
Fix committed
