### ISSUE TITLE
Explore the use of sets, curly braces vs set([])

### ISSUE THREAD

**Issue by ankenyr** [google/capirca#94]
From https://github.com/google/capirca/pull/83#discussion_r72572060

There is a bit of efficiency to be gained from switching over to using curly braces. It would be worth doing some profiling and timing of capirca to see if this could shave off a few seconds. If so we can use curly braces to create sets. If not we should standardize on using set([]).

My personal opinion is that set([]) is slightly more readable but if a performance increase could be seen by switching it may make sense to do so.

**Comment by ryantierney513** [comment]
My personal preference is {} versus set() but that's because sneakywombat trained me that way.

**Comment by finfinack** [comment]
I haven't read the history of #83 so maybe my comment can be ignored but a set() and a dict() / {} are different data types. Shouldn't the data type decide which should be used? I guess the keys of a dict can be (ab)used as a set but imo we shouldn't do that. If we don't need a unique set, use a list?

**Comment by ankenyr** [comment]
They are different data types @finfinack but the invocation can be similar and confusing.

Currently we invoke sets as such
`foo = Set([1, 2, 3])`

You can also create a set like this
`foo = {1, 2, 3}`

The second one has the advantage of having fewer calls made and thus is quicker.

The thing that makes it less readable in my mind is that both dicts and sets share curly braces. There is also the problem of creating an empty set.

```
foo = {}
bar = Set([])
```

Foo will always be a dict, you need to create an empty set like bar.
So the question is should we switch the creation of sets with items in them over to using curly braces? There are some instances of us creating blank sets, some instances of us using set to "uniq" a list, and some examples of us just creating a set of items.

**Comment by finfinack** [comment]
Ahhh, thanks for the background. That makes sense.

In that case, I think I'm with you. If there's a reasonable efficiency gain, I'd do it, otherwise I think the current way is cleaner.

I thought you wanted to use dicts instead :) I've never used {} for sets so far.

**Comment by ankenyr** [comment]
https://github.com/google/capirca/commit/f2ca4dff1c8037b8588c00867dcab61182b701a7 held this up a bit. I kept running into what was essentially an infinite loop and kept getting dragged away from troubleshooting by other problems. Will be able to do some profiling now that we are not iterating over every host in a very large IPv6 address.

**Comment by nero85** [comment]
Closing due to age.
