### ISSUE TITLE
base_directory argument doesn't work

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#95]
Using the latest trunk revision.
This used to work at least before the large effort that has been put into capirca a few months ago.

```
python aclgen.py --definitions_directory ./def --optimize --output_directory ./filters --policy_file ./policies/pol/test/borders_RE_firewall.pol
```
Properly generates a .jcl file.

While the following (where "borders_RE_firewall.pol" is the only file in /test/ doesn't generate the file (nor outputs an error message)
```
python aclgen.py --definitions_directory ./def --optimize --output_directory ./filters --base_directory ./policies/pol/test/
```
Please let me know how I can help troubleshooting it or if I'm not using it correctly.

Thanks!

**Comment by ankenyr** [comment]
DescendRecursively in aclgen.py is what controls this and the name is not entirely accurate. It will descend recursively looking for folders named "pol" but won't continue recursion past a pol directory. I suspect if you move that policy file up on directory it will see it and create the correct syntax. Let me know if it doesn't or if you strongly feel that there is a reason you would want your directory structured like above we can discuss that.

**Comment by XioNoX** [comment]
Thanks,
If I specify "--base_directory ./policies/pol/" it still doesn't work, but "--base_directory ./policies/ " (with the .pol file in the /pol/ directory) it works.
